### ISSUE TITLE
Keybindings conflict

### ISSUE THREAD

**Issue by bizoo** [mikefowler/simple-clone#1]
Nice plugin, thanks for sharing.

The keybindings are already used by ST2:

```
    { "keys": ["ctrl+shift+right"], "command": "move", "args": {"by": "word_ends", "forward": true, "extend": true} },
    { "keys": ["ctrl+shift+down"], "command": "swap_line_down" },
```

It's rather difficult to find a free keybinding today, so IMHO the best way to deal with them is to ask the users to defined what they want in their user config and suggest something as example  in the readme.

**Comment by mikefowler** [comment]
You're right, it's tough to find something that isn't already used by default, nevermind by another package. The defaults were what made most sense to me, but perhaps you're right. Thanks for the feedback!

**Comment by mattbolt** [comment]
This issue can probably be closed now with the addition of new changes allowing keybinds to be disabled

**Comment by mikefowler** [comment]
Agreed. Thanks for the updates, @mattbolt, I appreciate it.

**Comment by mattbolt** [comment]
You're most welcome ... The plugin was exactly what I was looking for, but these two keybinds particularly are things I use virtually every day. Figured I'd do something about it :smile:
